org: jsguaman7
app: examenjhonapp
service: examenjhon

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:430861662846:table/productosBoutique
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type

functions:
  agregarProducto:
    handler: src/agregarProducto.agregarProducto
    events:
      - httpApi:
          path: /productos
          method: post

  obtenerProductos:
    handler: src/obtenerProductos.obtenerProductos
    events:
      - httpApi:
          path: /productos
          method: get

  obtenerProducto:
    handler: src/obtenerProducto.obtenerProducto
    events:
      - httpApi:
          path: /productos/{id}
          method: get

  actualizarProducto:
    handler: src/actualizarProducto.actualizarProducto
    events:
      - httpApi:
          path: /productos/{id}
          method: put

  eliminarProducto:
    handler: src/eliminarProducto.eliminarProducto
    events:
      - httpApi:
          path: /productos/{id}
          method: delete

resources:
  Resources:
    productosBoutique:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productosBoutique
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
